[install-dependencies]
    description = "Install dependencies"
    run         = "npm install"

[serve]
    description = "Serve api with hot reloading on changes"
    depends     = "install-dependencies"
    run         = "npx vite --open --host"

[clean]
    description = "Remove all untracked or safe to remove files"
    run         = "git clean -fdx"

[format]
    description = "Format all files"
    run         = ["mise fmt", "npm run check"]
